### ISSUE TITLE
Fehlende list_free Funktion in überarbeiteter Tag9.Aufgabe1

### ISSUE THREAD

**Issue by malteklaassen** [SirkoHoeer/progkurs#5]
In Commit ddb9a72 wurde neben der (unnötigen) `list_create` auch die (didaktisch) extrem sinnvolle Funktion `list_free` aus der Aufgabestellung entfernt. Diese sollte (wenn es jetzt auch etwas spät ist) noch hinzugefügt werden.

**Comment by SirkoHoeer** [comment]
mit der Überarbeitung der Aufgaben werde ich diese Fehler noch beseitigen.
