### ISSUE TITLE
Veröffentlichung der Aufgabenblatt Sourcen

### ISSUE THREAD

**Issue by malteklaassen** [SirkoHoeer/progkurs#6]
Wäre es möglich die Sourcen der Aufgabenblätter online zu stellen? Dies könnte sowohl für zukünftige Dozenten des Vorkurses als auch zur Korrektur von Möglichen Fehlern in Aufgabenblättern von Interesse sein.

**Comment by SirkoHoeer** [comment]
Kein Problem, das mach ich noch

**Comment by SirkoHoeer** [comment]
erledigt
